baseURL: https://example.com
disableKinds:
  - section
  - taxonomy
  - term
  - RSS
  - robotsTXT
defaultContentLanguage: en
theme: hugo-scroll
title: Motel Rex - Bar & Motel # doesn't change actual title! --> content/_index.md
params:
  copyright: © Motel Rex - Bar & Motel
  description: Motel Rex - Bar & Motel
  favicon: images/favicon-umbrella.png 
  images: images/cover-image_1.jpg # doesn't change picture --> content/_index.md
  meta:
    keywords: some, keywords, for, seo, you, know, google, duckduckgo, and, such
  title: Motel Rex - Bar & Motel # doesn't change actual title! --> content/_index.md
