[build]
command = 'hugo'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.109.0'
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context]
[context.branch-deploy]
command = 'hugo -F -b https://www.motel-rex.ch'

[context.deploy-preview]
command = 'hugo -F -b https://www.motel-rex.ch'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
