[build]
command = 'hugo'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.109.0'
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
<<<<<<< HEAD
<<<<<<< HEAD

[headers]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "https://www.motel-rex.ch/*"
=======
>>>>>>> b8d820ad8eea463060643f8a2e1422d571483bd7
=======

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
>>>>>>> 9060abc424d6d007e628a1c89d7728217937135f
